/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2024-01-17 17:58:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("d\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <title>EHEI Transfer</title>\n");
      out.write("\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"style/style.css\">\n");
      out.write("  <link rel=\"icon\" type=\"image/x-icon\" href=\"img/logo_haute_qualité.png\">\n");
      out.write("\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<section class=\"vh-100\">\n");
      out.write("  <div class=\"container-fluid h-custom\">\n");
      out.write("    <div class=\"row d-flex justify-content-center align-items-center h-100\">\n");
      out.write("      <div class=\"col-md-9 col-lg-6 col-xl-5\">\n");
      out.write("        <img src=\"img/acc.png\"\n");
      out.write("             class=\"img-fluid\" alt=\"Sample image\">\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-8 col-lg-6 col-xl-4 offset-xl-1\">\n");
      out.write("        <form method=\"get\">\n");
      out.write("\n");
      out.write("          <div>\n");
      out.write("\n");

      out.write("          </div>\n");
      out.write("\n");
      out.write("          <!-- Email input -->\n");
      out.write("          <div class=\"form-outline mb-4\">\n");
      out.write("            <input type=\"email\" id=\"form3Example3\" class=\"form-control form-control-lg\"\n");
      out.write("                   placeholder=\"Enter a valid email address\" />\n");
      out.write("            <label class=\"form-label\" for=\"form3Example3\">Email address</label>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <!-- Password input -->\n");
      out.write("          <div class=\"form-outline mb-3\">\n");
      out.write("            <input type=\"password\" id=\"form3Example4\" class=\"form-control form-control-lg\"\n");
      out.write("                   placeholder=\"Enter password\" />\n");
      out.write("            <label class=\"form-label\" for=\"form3Example4\">Password</label>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"d-flex justify-content-between align-items-center\">\n");
      out.write("            <!-- Checkbox -->\n");
      out.write("            <div class=\"form-check mb-0\">\n");
      out.write("              <input class=\"form-check-input me-2\" type=\"checkbox\" value=\"\" id=\"form2Example3\" />\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"text-center text-lg-start mt-4 pt-2\">\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary btn-lg\"\n");
      out.write("                    style=\"padding-left: 2.5rem; padding-right: 2.5rem;\">Login</button>\n");
      out.write("            <p class=\"small fw-bold mt-2 pt-1 mb-0\">Don't have an account? <a href=\"Register.jsp\"\n");
      out.write("                                                                              class=\"link-danger\">Register</a></p>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div\n");
      out.write("          class=\"d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary\">\n");
      out.write("    <!-- Copyright -->\n");
      out.write("    <div class=\"text-white mb-3 mb-md-0\">\n");
      out.write("      Copyright © 2020. All rights reserved .\n");
      out.write("      <a href=\"http://tech-nova.site\"> devloped by Technova </a>\n");
      out.write("    </div>\n");
      out.write("    <!-- Copyright -->\n");
      out.write("\n");
      out.write("    <!-- Right -->\n");
      out.write("    <div>\n");
      out.write("      <a href=\"#!\" class=\"text-white me-4\">\n");
      out.write("        <i class=\"fab fa-facebook-f\"></i>\n");
      out.write("      </a>\n");
      out.write("      <a href=\"#!\" class=\"text-white me-4\">\n");
      out.write("        <i class=\"fab fa-twitter\"></i>\n");
      out.write("      </a>\n");
      out.write("      <a href=\"#!\" class=\"text-white me-4\">\n");
      out.write("        <i class=\"fab fa-google\"></i>\n");
      out.write("      </a>\n");
      out.write("      <a href=\"#!\" class=\"text-white\">\n");
      out.write("        <i class=\"fab fa-linkedin-in\"></i>\n");
      out.write("      </a>\n");
      out.write("    </div>\n");
      out.write("    <!-- Right -->\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
